build-klodx-ui-prod:
  stage: build
  environment:
    name: PROD
    url: https://klodx-ui-prod.bitcofe.com
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - env | grep 'KLODX_' | sed 's/KLODX_//' > variables.env
    - docker pull $CI_REGISTRY_IMAGE:dependencies-latest
    - docker build --target builder-stage -t $CI_REGISTRY_IMAGE:prod-$CI_PIPELINE_ID .
  tags: 
    - runner-server-01-shell

release-klodx-ui-prod:
  stage: release
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker tag $CI_REGISTRY_IMAGE:prod-$CI_PIPELINE_ID $CI_REGISTRY_IMAGE:prod-latest
    - docker push $CI_REGISTRY_IMAGE:prod-$CI_PIPELINE_ID
    - docker push $CI_REGISTRY_IMAGE:prod-latest
  tags: 
    - runner-server-01-shell

deliver-klodx-ui-prod:
  stage: deliver
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE:prod-$CI_PIPELINE_ID
  tags: 
    - klodx-prod-shell

deploy-klodx-ui-prod:
  stage: deploy
  environment:
    name: PROD
    url: https://klodx-ui-prod.bitcofe.com
  script:
    - echo "DEPLOY_NAME=prod" > .env
    - echo "TAG_NAME=prod-${CI_PIPELINE_ID}" >> .env
    - echo "EXPOSED_PORT=${KLODX_EXPOSED_PORT}" >> .env
    - env | grep 'KLODX_' | sed 's/KLODX_//' >> variables.env
    - docker compose -f compose.yml up -d
  tags:
    - klodx-prod-shell
  