build-klodx-ui-stage:
  stage: build
  environment:
    name: STAGE
    url: https://klodx-ui-stage.bitcofe.com
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - env | grep 'KLODX_' | sed 's/KLODX_//' > variables.env
    - docker pull $CI_REGISTRY_IMAGE:dependencies-latest
    - docker build --target builder-stage -t $CI_REGISTRY_IMAGE:stage-$CI_PIPELINE_ID .
  only:
    refs:
      - stage
  tags: 
    - runner-server-01-shell

release-klodx-ui-stage:
  stage: release
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker tag $CI_REGISTRY_IMAGE:stage-$CI_PIPELINE_ID $CI_REGISTRY_IMAGE:stage-latest
    - docker push $CI_REGISTRY_IMAGE:stage-$CI_PIPELINE_ID
    - docker push $CI_REGISTRY_IMAGE:stage-latest
  tags: 
    - runner-server-01-shell

deliver-klodx-ui-stage:
  stage: deliver
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE:stage-$CI_PIPELINE_ID
  tags: 
    - klodx-stage-shell

deploy-klodx-ui-stage:
  stage: deploy
  environment:
    name: STAGE
    url: https://klodx-ui-stage.bitcofe.com
  script:
    - echo "DEPLOY_NAME=stage" > .env
    - echo "TAG_NAME=stage-${CI_PIPELINE_ID}" >> .env
    - echo "EXPOSED_PORT=${KLODX_EXPOSED_PORT}" >> .env
    - env | grep 'KLODX_' | sed 's/KLODX_//' >> variables.env
    - docker compose -f compose.yml up -d
  tags:
    - klodx-stage-shell
  